# Site settings
title: Hi!
email: michelleamesquita@gmail.com
description: Made by <3.
baseurl: "/identity-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Michelle Mesquita
your-title: Cybersecurity girl <3

# Social settings
500px_url: https://google.com
# facebook_url: 
github_url: https://github.com/michelleamesquita
# gitlab_url: 
# googleplus_url: 
# instagram_url: 
linkedin_url: https://www.linkedin.com/in/michelleamesquita
# pinterest_url:
# slack_url:
# twitter_url: 

# Build settings
markdown: kramdown
